#!/bin/sh

# check: installer -pkg rvault-0.$ver.pkg -target / -verbose -dumplog

set -eu

log_file="$HOME/Library/Logs/rvault-installer.log"

error_msg()
{
	local title="An error has occurred."
	local msg="$1"

	echo "display alert \"$title\" message \"$msg\" as critical" | \
	    osascript > /dev/null || true
	(date; echo "$msg") > $log_file 2>&1 || true
	exit 1
}

error_dep_msg()
{
	local msg=$(cat <<-EOF
	The following dependencies are needed by rvault:

	$1 FUSE for macOS: https://macfuse.github.io/

	$2 Homebrew package manager: https://brew.sh/

	Please follow the installation instructions on these web sites.

	Additionally, the following Homebrew packages are required:

	$3 OpenSSL: brew install openssl
	$4 libscrypt: brew install libscrypt

	Run the commands above to install them.
	$5
	EOF
	)
	error_msg "$msg"
}

# ✓ ✘ •
failed=""
d1="✓"; d2="✓"; d3="✓"; d4="✓";
check=""

test -f "/usr/local/lib/libfuse.dylib" || { failed=1; d1="✘"; }
test -f "/opt/homebrew/bin/brew" || { failed=1; d2="✘"; }
test -f "/opt/homebrew/opt/openssl/lib/libssl.dylib" || { failed=1; d3="✘"; }
test -f "/opt/homebrew/opt/libscrypt/lib/libscrypt.dylib" || { failed=1; d4="✘"; }
$INSTALLER_PAYLOAD_DIR/usr/local/bin/rvault --version >/dev/null 2>&1 || {
	failed=1;
	check="$($INSTALLER_PAYLOAD_DIR/usr/local/bin/rvault --version 2>&1)";
}

[ -z "$failed" ] || {
	error_dep_msg "$d1" "$d2" "$d3" "$d4" "$check";
	exit 1;
}
