language: c

compiler:
  - gcc
  - clang

dist: bionic

matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
    # Travis transient failures
    - os: linux
      arch: ppc64le
    # Travis transient failures
    - os: osx
      osx_image: xcode11.3

addons:
  apt:
    update: true
    packages:
    - build-essential
    - fakeroot
    - debhelper
    # crypto libraries:
    - libssl-dev
    - libsodium-dev
    - libmbedtls-dev
    # mandatory dependencies:
    - libscrypt-dev
    - libfuse-dev
    - libcurl4
    # optional dependencies:
    - libedit-dev
    - liblz4-dev
    - libsqlite3-dev
    - liblua5.3-dev
    - lua5.3

  homebrew:
    update: false
    packages:
    - libscrypt
    - lz4
    - openssl@1.1
    - libsodium
    - mbedtls
    - lua
    casks:
    - osxfuse

script:
  # Build and install the DEB packages.
  - if [ "$(uname -s)" = "Linux" ]; then (cd pkg && make deb && sudo dpkg -i ../rvault*.deb); fi
  # Run the unit tests.
  - (cd src && make clean && USE_LZ4=1 make -j4 tests)
  # Run the Lua tests.
  - (cd src && make clean && make -j4 lib && make lua-tests)
  #
  # Run the tests using mbedtls and libsodium
  #
  #- (cd src && USE_MBEDTLS=1 make clean && USE_OPENSSL=0 USE_MBEDTLS=1 make tests)
  - if [ "$(uname -n)" = "x86_64" ]; then (cd src && USE_SODIUM=1 make clean && USE_OPENSSL=0 USE_SODIUM=1 make tests); fi
