language: c

compiler:
  - gcc
  - clang

dist: bionic

matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
    # Travis transitional failures
    #- os: linux
    #  arch: ppc64le
    - os: osx
      osx_image: xcode11.2

addons:
  apt:
    update: true
    packages:
    - build-essential
    - fakeroot
    - debhelper
    - libssl-dev
    - libscrypt-dev
    - libreadline-dev
    - libfuse-dev
    - liblua5.3-dev
    - lua5.3
  homebrew:
    update: true
    packages:
    - openssl@1.1
    - libscrypt
    - lua
    casks:
    - osxfuse

script:
  # Run the unit tests.
  - (cd src && make clean && make -j4 && make tests)
  # Run the Lua tests.
  - (cd src && make clean && make -j4 lib && make lua-tests)
